#!/bin/bash
RED="\e[31m"
GREEN="\e[32m"
SET="\e[0m"

echo "Paste migimap lines below:"
migvars=`cat | sed '/^$/d'`
numVars=`echo $migvars | wc -w`
numLines=`echo $migvars | wc -l`
numCheck=$(echo "scale=2; $numVars / 6" | bc)

umask 0000

if [[ $numCheck =~ ^-?[0-9]+.00$ ]]; then
  echo -e "\nMigrating $numLines email account(s) to Bluehost."
  { while IFS=' ' read host1 user1 pass1 host2 user2 pass2
    do
      imapsync --exclude Calendar --exclude Contacts --useuid --automap --nosyncacls --syncinternaldates --tmpdir /tmp/imapsync --logdir /tmp/imapsync/log --logfile ${user1}.log --pidfile /tmp/imapsync/pid/${user1} --pidfilelocking \
          --host1 $host1 --user1 $user1 --password1 $pass1 \
          --host2 $host2 --user2 $user2 --password2 $pass2 $@
    done
  } <<< "$migvars"
  echo -e "\n\t=========================== Results ==========================="
  { while IFS=' ' read host1 user1 pass1 host2 user2 pass2
    do
      eUser=`echo -e "\t\t\t$user1" | tr [a-z] [A-Z]`
      results=`egrep 'Start' /tmp/imapsync/log/${user1}.log`
      results1=`egrep 'Final' /tmp/imapsync/log/${user1}.log`
      results2=`egrep 'Detected' /tmp/imapsync/log/${user1}.log`
      results3=`egrep 'Host1 failure' /tmp/imapsync/log/${user1}.log`
      results4=`egrep -i "Host2 failure|couldn't append" /tmp/imapsync/log/${user1}.log | sort -u`
      successMes=`egrep 'Exiting with return value 0' /tmp/imapsync/log/${user1}.log | sed 's,Exiting with return value 0,Success,g'`
      [ ! -z "$successMes" ] && echo -e "${GREEN}${eUser}: ${successMes}${SET}" || echo -e "${GREEN}${eUser}:${SET} ${RED}Failure${SET}"
      [ ! -z "$results" ] && echo -e "\t${results}"
      [ ! -z "$results1" ] && echo -e "\t${results1}"
      [ ! -z "$results2" ] && echo -e "\t${results2}"
      [ ! -z "$results3" ] && echo -e "\t${results3}"
      [ ! -z "$results4" ] && echo -e "\t${results4}"
    done
  } <<< "$migvars"
else
  echo -e "${RED}$Error:${SET} Should be 6 fields for each line in the input. Please review."
fi
